workflows:
  ios-workflow:
    name: iOS Production Workflow
    environment:
      groups:
        - app_store_credentials  # Set these in Codemagic UI
      vars:
        FLUTTER_VERSION: "3.19.5"  # Match your Flutter version
        BUNDLE_ID: "com.yourcompany.yourapp"  # Your bundle identifier
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up Flutter
        script: |
          flutter channel stable
          flutter upgrade $FLUTTER_VERSION
          flutter precache --ios
          flutter doctor -v

      - name: Install dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          cd ios
          pod install

    building:
      ios: 
        name: Build IPA
        project: ios/Runner.xcodeproj
        scheme: $XCODE_SCHEME
        device: any_ios_device
        signing:
          automatic:
            team_id: $APP_STORE_TEAM_ID  # Set in environment variables
            bundle_identifier: $BUNDLE_ID
            certificate_type: apple_distribution
        xcode:
          project_build_settings:
            automatic_code_signing: true
        generate_archive: true

    publishing:
      app_store_connect:
        auth: api_key
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        api_key: $APP_STORE_API_KEY
        submit_to_app_store: true  # Set to false for TestFlight only
      email:
        recipients:
          - your.team@example.com
      scripts:
        - name: Upload to Firebase
          script: |  # Example additional step
            flutter pub run flutterfire_cli:activate
            firebase appdistribution:distribute build/ios/ipa/*.ipa \
              --app "$FIREBASE_IOS_APP_ID" \
              --groups "testers" \
              --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log

# Required environment variables to set in Codemagic UI:
# APP_STORE_KEY_ID          - App Store Connect API Key ID
# APP_STORE_ISSUER_ID       - App Store Connect API Issuer ID
# APP_STORE_API_KEY         - App Store Connect API Key (content)
# APP_STORE_TEAM_ID         - Apple Developer Team ID
# FIREBASE_IOS_APP_ID       - Optional for Firebase distribution
# FIREBASE_TOKEN            - Optional for Firebase distribution
